### ISSUE TITLE
Unable to proceed past the NPC Degenhard part of the Black Belt quest

### ISSUE THREAD

**Issue by almuth150** [topaz-next/topaz#2285]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
When you reach the point where you talk to Degenhard for the quest "Beat Around the Bushin", you are unable to continue with the quest. The cutscene plays, but you never get registered as having viewed it, and you get some message about another event. This might be because the script is starting two events at once (see: https://github.com/topaz-next/topaz/blob/release/scripts/zones/Bastok_Markets/npcs/Degenhard.lua#L27) - previous versions of the script did not attempt to also start event 15. Unfortunately, I do not have a test environment to be able to see if this is the problem with 100% certainty, so I'm submitting a bug report instead of attempting to fix it.

My client version is 30201103_3, if that is of any meaning. Apologies if I'm not supposed to submit this since I'm not actually working on the project.

**Comment by zach2good** [comment]
Hi! Thanks for digging into this, that event is already mentioned in the trade block, so I've just ninja'd in its removal:
https://github.com/topaz-next/topaz/commit/0c96a1fbe7407b555caca54c8b60b22706a8609b

If you could follow up on if that fixed the issue that would be super helpful 👍

**Comment by almuth150** [comment]
I will let the devs on the server I play on know about this. Thank you. I don't know the timeline for when I'll be able to know about this, but I'll let you know when I do.

However, I do know the quest had worked in a much older build, and while that may be a long time ago, this NPC script hasn't changed much in actual functionality.

**Comment by tristamgreen** [comment]
hi @zach2good i have cloned this on our server and it'll be fixed for good when we rebase again to this (if/when)

Thanks for taking time to look into this

**Comment by almuth150** [comment]
This seems to be fixed. If anything went wrong, I suppose I could always (re)open this issue. Thank you.
