### ISSUE TITLE
can't trade item for guildpoints in bonecrafting and goldsmithing

### ISSUE THREAD

**Issue by kaincenteno** [topaz-next/topaz#2287]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

This was reported by myguri in canaria:

Myguri:
```My Bonecrafting skill is 90 and my rank is Veteran.  Samigo-Pormigo asked for a carapace helm for guild points.  I could not trade for points.  We switched guilds to Goldsmithing.  My GS skill is 51 and my rank is journeyman.  Ellard asked for a heater shield, which I crafted and gave him but he did not accept.```

I checked the crafting.lua global and its receiving zeroes for items and points variables in 
```lua
                local items, points = player:addGuildPoints(guildID, i)
```

Myguri talked to the NPC and verified that the item asked is the correct one and that their character is still is able to receive more points.

**Comment by bope12** [comment]
so in src/map/guild.cpp line 123 its checking if players daily points are zero rather then checking if you have reached cap for the item
` if (curPoints == 0)`
below works but does not take into effect if you rank up and the curpoints get reset to -1, I was going to do both together in a PR but got side tracked so if someone wanted to this at least gets it working back to how it was before this zero worked its way in.
` if (curPoints == GPItem[0].maxpoints)`

**Comment by EpicTaru** [comment]
So after changing guilds did the player wait until JP midnight? You aren't allowed to obtain GP in the new guild until the next earth day (JP midnight).

**Comment by kaincenteno** [comment]
ah i see, i saw one of the charvars set to -1 so i guess it needs to wait another day. Thank you @bope12 i'll ask to try tomorrow see how it goes

**Comment by bope12** [comment]
> 
> 
> ah i see, i saw one of the charvars set to -1 so i guess it needs to wait another day. Thank you @bope12 i'll ask to try tomorrow see how it goes

It will still fail on new day all dailyvars are set to zero and its checking if the var is zero and calling that capped

**Comment by kaincenteno** [comment]
im confused what do you mean @bope12 ?

this is from myguri today after JPN midnight:

```
It says "you are not eligible to receive guild points at this time.
[12:06 PM]
remember yesterday it did give a value
[12:06 PM]
now that jp midnight has passed, i am no longer eligible somehow
```

**Comment by Era-Lusiphur** [comment]
Same for Clothcrafting.

Two days in a row, unable to turn in either following JP midnight or Canaria's daily reset time. Did not rank up between first and second day or any other activities that should have interfered with it.

Edit: Now three days.

**Comment by RAIST5150** [comment]
Not working for cooking today either.

Not doing points with any other guild, and has been at least a week or two since my last interaction with the NPC where I traded items and bought a KI, leaving 100 points in the bank.
