### ISSUE TITLE
Throwing animation is incorrect

### ISSUE THREAD

**Issue by ShiyoKozuki** [topaz-next/topaz#2325]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1) Equip a "throwing" weapon such as dart or shuriken. 
2) Try to /ra. 

You will now do the singing without an instrument equipped animation.  I do not have lockstyle on

I have tried with lockstyle to a dart, lockstyle to an xbow, lockstyle to an arrow, lockstyle to a bow, lockstyle to a shuriken, and lockstyle off. All of them result in the same bug.

**Comment by Flam9** [comment]
For future readers, how did you resolve this?

**Comment by ShiyoKozuki** [comment]
I didn't, I just shouldn't have opened this as I found the same issue in another report.

**Comment by zach2good** [comment]
https://github.com/topaz-next/topaz/issues/895
