### ISSUE TITLE
getEnemies no longer exists, but is referenced in allyassist global

### ISSUE THREAD

**Issue by wrenffxi** [topaz-next/topaz#2336]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://github.com/topaz-next/topaz/blob/release/scripts/globals/allyassist.lua#L20

**Comment by zach2good** [comment]
Interesting find!

This has been gone since the end of DSP, but there's no reason we can't just add it in, I'll do that later 👍

**Comment by zach2good** [comment]
Scrap that, I guess this has been superceeded by getMobs:
```cpp
CLuaBattlefield:
    int32 getPlayers(lua_State*);
    int32 getMobs(lua_State*);
    int32 getNPCs(lua_State*);
    int32 getAllies(lua_State*);
```
