### ISSUE TITLE
Merit Point for DEX charging wrong price

### ISSUE THREAD

**Issue by kaincenteno** [topaz-next/topaz#2350]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Merit Point for DEX 14 charges 19 merit points instead of 18

**Comment by ghost** [comment]
Issue should be fixed in #2390

**Comment by kaincenteno** [comment]
Awesome thank you @claywar
