### ISSUE TITLE
NPC "Nenepp" (17801297) is underground

### ISSUE THREAD

**Issue by Besbe** [topaz-next/topaz#2353]
**_I have:_**

- [] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

1. Log in Topaz with any character
2. Port to NPC "Nenepp" (!gotoid 17801297)
3. --> The NPC is underground

Please note that Nenepp.lua has a roaming path meaning that changing its position on the DB won't solve the problem.

![image](https://user-images.githubusercontent.com/75217612/103486673-50347800-4db4-11eb-9a11-ec391c9bc2e5.png)

**Comment by ghost** [comment]
Pathing related issue (from similar issue reports):
![image](https://user-images.githubusercontent.com/12447174/110012639-ba9f6100-7cee-11eb-9d87-bb6918d85ecb.png)
