### ISSUE TITLE
Enspell elements incorrect

### ISSUE THREAD

**Issue by ShiyoKozuki** [topaz-next/topaz#2358]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Enspells are currently not assigned the correct element. I have tested them by attacking elementals where I coded their resistances to match retail, and double checked I did this corrrectly by nuking them with normal elemental nukes.

Here are the damage types of every enspell:

Enstone - Thunder Damage
Enthunder - Water damage
Enwater - Light Damage
Enblizzard - Air damage
Enaero - Earth  damage
Enfire - Ice Damage

**Comment by TeoTwawki** [comment]
The "what its weak to" vs "what its strong to" are flipped. if you look they aren't just "wrong" they are exactly opposite.

**Comment by TeoTwawki** [comment]
nvm whole table screwy

**Comment by wrenffxi** [comment]
fixed in sol_refactor. will close issue once it lands in release.

**Comment by wrenffxi** [comment]
closed via #2377 and #2431 merging into release
