### ISSUE TITLE
[Magian] Preview require item and reward item doesn't work

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2362]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

- Trade a weapon for start trial
- Select trial 
-  Select required item or reward item

See the video

https://user-images.githubusercontent.com/1618002/103593071-1a4add00-4ef5-11eb-8f63-9ff1a62a7fd9.mp4

**Comment by ghost** [comment]
Guessing that we're not passing the correct parameters into updateEvent.  Can anyone get some retail captures for this?

**Comment by ghost** [comment]
Hi @Chronos77 can you double-check this issue?  I just tried with the same item on my end on sol_refactor, and it seems to be working properly.

Note: There is another issue we're running down where the item isn't returned in some cases if cancelling out of CS

**Comment by ghost** [comment]
Also, are you by chance using the eternity plugin?  Zach was having a similar issue yesterday with that plugin enabled for a different event.

**Comment by Chronos77** [comment]
Indeed it is this plugin. it's the same behaviour on retail

**Comment by zach2good** [comment]
That was driving me insane when I was seeing that behaviour while working on something similar :D

**Comment by TeoTwawki** [comment]
enternity and frame rate modifications are known to make cut scene events screwy (frame rate tends to get them stuck) some other addon/plugin too but I don't have a list
