### ISSUE TITLE
"QUESTS ID" spelling mistake

### ISSUE THREAD

**Issue by eyes-and-brain** [topaz-next/topaz#2366]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://github.com/project-topaz/topaz/blob/b9517bdf814ff8f249348e44e9b89e5489e64c23/scripts/globals/quests.lua#L298-L300

The correct spelling of "TO_CATCH_A_FALLIHG_STAR" is "TO_CATCH_A_FALLING_STAR" ? (L299)

**Comment by eyes-and-brain** [comment]
Addition.

https://github.com/project-topaz/topaz/blob/b9517bdf814ff8f249348e44e9b89e5489e64c23/scripts/globals/quests.lua#L687-L689

The correct spelling of "WAKING_THE_COLLOSSUS" is "WAKING_THE_COLOSSUS" ? (L688)

**Comment by wrenffxi** [comment]
fixed in sol_refactor.  will close issue once it lands in release.

**Comment by wrenffxi** [comment]
closed via #2375 merging into release
