### ISSUE TITLE
[sol_refactor] Food effect GetSubID() crash

### ISSUE THREAD

**Issue by Omnione** [topaz-next/topaz#2371]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

**Action to reproduce:**  eat food or zone with food on.
**file:**  status_effect_container.cpp
**function:**  void CStatusEffectContainer::SetEffectParams(CStatusEffect* StatusEffect)
**error line:**  1316 -> TPZ_DEBUG_BREAK_IF(StatusEffect->GetStatusID() == EFFECT_FOOD && StatusEffect->GetSubID() == 0);

**Comment by zach2good** [comment]
Should be fixed with https://github.com/topaz-next/topaz/pull/2373
