### ISSUE TITLE
[sol_refactor] Command injectation not working

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2387]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
write commands : !injectation 2 630
An error appear in the logs:
![image](https://user-images.githubusercontent.com/1618002/103835368-624d3980-5086-11eb-8caa-1a2aaccccc2e.png)

**Comment by ghost** [comment]
Currently, CLuaBaseEntity::injectActionPacket requires all parameters to be populated, and is failing from nil values received for the last 3.  Fix incoming.

**Comment by Chronos77** [comment]
We can close ? I tested the commit and it's work !

**Comment by ghost** [comment]
I believe this issue can be closed.  I only made changes to the !command, and not the injectActionPacket function, so if for some reason that is used for anything else in the future, it will still require all arguments passed to it.

**Comment by Chronos77** [comment]
Ok, fix #2388
