### ISSUE TITLE
SMN pets and probly other pets not having correct stats

### ISSUE THREAD

**Issue by Omnione** [topaz-next/topaz#2396]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

SMN pets and probly other pets do not calculate stats correctly currently.

The issue seems to point to a simular issue with trust stats not being calculated correctly,
in petentity.cpp, we are spawning a pet as CMobEntity::Spawn();, when it should probably be 
CBattleEntity::Spawn();, tested this and stats are correct, not sure if other funtions will suffer the same issue.

**Comment by zach2good** [comment]
Yup, automated `clang-tidy` run shuffled a bunch of things around, in this commit: https://github.com/topaz-next/topaz/commit/eb273bb3e7bbd70fddc0a69090f30166ae711610

I've gone through that commit and found the following (everything else seems sane):

Automatons are fine (but they're broken in general anyway), Char, Battle, NPC are fine

Trust and Pet need to have these rolled back:
```
    CBattleEntity::PostTick();
    CMobEntity::PostTick();
    
    CBattleEntity::Die();
    CMobEntity::Die();
    
    CBattleEntity::Spawn();
    CMobEntity::Spawn();

    CBaseEntity::FadeOut();
    CMobEntity::FadeOut();

    CBattleEntity::OnCastFinished(state, action);
    CMobEntity::OnCastFinished(state, action);

    CBattleEntity::OnWeaponSkillFinished(state, action);
    CMobEntity::OnWeaponSkillFinished(state, action);
```

**Comment by zach2good** [comment]
The rule to watch out for in the future it this: https://clang.llvm.org/extra/clang-tidy/checks/bugprone-parent-virtual-call.html

I've blocked this in our `clang-tidy` file 🙏 

**bugprone-parent-virtual-call**

Detects and fixes calls to grand-…parent virtual methods instead of calls to overridden parent’s virtual methods.

```cpp
struct A {
  int virtual foo() {...}
};

struct B: public A {
  int foo() override {...}
};

struct C: public B {
  int foo() override { A::foo(); }
//                     ^^^^^^^^
// warning: qualified name A::foo refers to a member overridden in subclass; did you mean 'B'?  [bugprone-parent-virtual-call]
};
```

**Comment by zach2good** [comment]
Rolled back in commit: https://github.com/topaz-next/topaz/commit/b41ad84dcb7b0bf8ba405bbe26d6559715953f22
