### ISSUE TITLE
[sol_refactor] Sandspin displays damage that does not match

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2399]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
reference to issues #1110 (Check blu  spell magic)

I don't know if I am testing correctly but when i'm in !godmode we can see that

131071 damage when fafnir have 70k hp however he is not dead but at 96% 

![image](https://user-images.githubusercontent.com/1618002/104062454-d14b9f00-51fa-11eb-8504-d522ff9c22a7.png)

Edit: when i'm not in !godmode and !capallskill is exactly the same dmg  (131071 dmg)

Edit2: After 15x Sandspin add effect does not apply

**Comment by Chronos77** [comment]
And this error in the log :)
![image](https://user-images.githubusercontent.com/1618002/104064948-25588280-51ff-11eb-8000-d46f6a35f9a6.png)

**Comment by ghost** [comment]
I fixed the canGainStatusEffect function in #2401 , can you see if that also resolves the garbage value being displayed for damage?

**Comment by Chronos77** [comment]
it's ok for damage  and for the spell!
