### ISSUE TITLE
Removal of masks functions broke Lathuya.lua 's onEventFinish and onEventTrigger

### ISSUE THREAD

**Issue by kaincenteno** [topaz-next/topaz#2415]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Changes made in October's commit
https://github.com/project-topaz/topaz/commit/e0f2b0116c3ae1ea8b1446918cd263db796e7e39#diff-dcaa3294e15a4adab745513619c6bee1a3283d70270f4f6b0bd546f161bbd895
removed countMaskBits that is being used in Lathuya.lua in
https://github.com/topaz-next/topaz/blob/f222ae85dbe6779ac973165d4d290c594fdeec84/scripts/zones/Aht_Urhgan_Whitegate/npcs/Lathuya.lua#L144
and 
https://github.com/topaz-next/topaz/blob/f222ae85dbe6779ac973165d4d290c594fdeec84/scripts/zones/Aht_Urhgan_Whitegate/npcs/Lathuya.lua#L40

**Comment by wrenffxi** [comment]
fixed in sol_refactor. will close issue once it lands in release.

**Comment by wrenffxi** [comment]
closed via #2424 merging into release
