### ISSUE TITLE
Changejob issues

### ISSUE THREAD

**Issue by Gradius2** [topaz-next/topaz#2418]
Hi,

I know it seems not implemented, but I will post here anyway...

If I do a simple !changejob RUN 99, it works fine, it changes the job to that class.

However if I do the same for GEO, it just crashes the server.

Should at least not crashes?   Even if not implemented, it should be posible just to change the job, as with RUN (for example) it works fine.

Regards,
Gradius2

**Comment by wrenffxi** [comment]
Closed via #2423
