### ISSUE TITLE
[sol_refactor] Cannot healing

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2419]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Just /heal 
![image](https://user-images.githubusercontent.com/1618002/104244721-51743d80-5463-11eb-9ecf-d59a5834120d.png)

**Comment by Gradius2** [comment]
Hi,

This is odd, as I have created a char (BLM for example), after some nukes, EXP gain, etc, I just pressed * (same as /heal), and worked fine.

I know where that code is, but need more details.  Which class job?  Level?   Area?

Edit: btw, I compiled with the last VS2019 and as 64-bit.  I'm also using MariaDB v10.5 + updated HeidiSQL.

Effect ID: 794 means that... healing.

**Comment by Gradius2** [comment]
FYI...

Logged in.  Changed job to whm/blm.  Went to Bibiki Bay.  Took some hp/mp from char... heal... no error messages, and yes, it healed fine (both hp & mp).

The code is just this:
#include "../common/utils.h"

#include "entities/battleentity.h"
#include "status_effect.h"

#include "status_effect_container.h"
#include <utility>

CStatusEffect::CStatusEffect(EFFECT id, uint16 icon, uint16 power, uint32 tick, uint32 duration, uint32 subid, uint16 subPower, uint16 tier, uint32 flags)
: m_StatusID(id)
, m_SubID(subid)
, m_Icon(icon)
, m_Power(power)
, m_SubPower(subPower)
, m_Tier(tier)
, m_Flag(flags)
, m_TickTime(tick * 1000)
, m_Duration(duration * 1000)
{
    if (m_TickTime < 3000 && m_TickTime != 0)
    {
        ShowWarning("Status Effect tick time less than 3s is no longer supported.  Effect ID: %d\n", id);
    }
}

There are a bit more (code), but just to showing effects, set some variables, & misc.

**Comment by Chronos77** [comment]
Thank you for your feedback. i tried to go back before merging the sol_refactor branch and it looks good to me. I think there is a commit which should not be adapted compared to my config.  
Currently I had the tick time at 1 but I tried to put it> 3, but the problem occurs (just the warning less)
I tried with all characters (GM / not GM) WHM / BLM / BLU, * (/heal) does not work.

the two commits that I merge that trigger this problem are:
4de0401
dd2c65f

**Comment by Gradius2** [comment]
This is VERY strange, as I have no problem.

Are you sure you are using the last release?  Backup your DB, delete it (drop all) and import the last revision.

Also, are you on last FFXI client as well (fully updated)?

I changed jobs and in all of them is working fine.

As for frontend, I use Windower + xiloader.exe (compiled by me too).

Regards,
Gradius

**Comment by Chronos77** [comment]
"As for frontend, I use Windower + xiloader.exe (compiled by me too)."  same for me

I rebuilt a server from scratch. that is to say that I installed the server on a personal pc (windows 10). I started the server with Docker from the sol_refactor branch. the database was created with all the sql files present in the sql folder. I created a character (war) and tried to / heal and that dosen't  work :o

**Comment by ghost** [comment]
This issue should be resolved following a fix Wren is working on right now with roe records.  Some of the performance functionality caused some unintended side-effects, and is actively being resolved.

**Comment by Gradius2** [comment]
This is all very weird.  It's works perfectly on me.  I even changed job to war/nin, and heal do works fine.

**Comment by Gradius2** [comment]
[![](http://img.youtube.com/vi/esjJyOoX4Tg/0.jpg)](http://www.youtube.com/watch?v=esjJyOoX4Tg "video as proof")

**Comment by Chronos77** [comment]
Resolved ! thanks
