### ISSUE TITLE
[sol_refactor]  I got an error  with R0 on the server 

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2434]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

i dont know how i get this error i just played on the server with the sol_refactor branch

![image](https://user-images.githubusercontent.com/1618002/104654507-80392080-56bc-11eb-9e48-1deee37ad33e.png)

![image](https://user-images.githubusercontent.com/1618002/104654284-20427a00-56bc-11eb-8ab8-64c220e3f936.png)

<del>EDIT:
Ok I found a case.</del>

<del>I did two tests, one with only the GM character (without RoE active), everything is correct. However if I take any character in the party with many RoE active, the problem occurs. </del>

Link many mobs and kill everything (with one spell). 

The r0 occurs and the error message appears in the server logs

https://user-images.githubusercontent.com/1618002/104657128-baa4bc80-56c0-11eb-801b-99856f489859.mp4

EDIT EDIT: 
The first time I think it's because I activated a lot of roe including a lot that validates with each mob kill

**Comment by Chronos77** [comment]
Ok I found a case.

I did two tests, one with only the GM character (without RoE active), everything is correct. However if I take any character in the party with many RoE Active. 

Link many mobs and kill everything (with one spell). 

The r0 occurs and the error message appears in the server logs

https://user-images.githubusercontent.com/1618002/104657128-baa4bc80-56c0-11eb-801b-99856f489859.mp4

**Comment by zach2good** [comment]
Hmmmm, this doesn't look good for the filewatcher D:

Filewatcher is only switched on for DEBUG builds, so could you try and reproduce this with a RELEASE version? If you're on Linux you can configure that by using this during the build setup: `cmake -DCMAKE_BUILD_TYPE=Release ..`

**Comment by Chronos77** [comment]
I build with docker, however I had to comment out the code on the filewatchers because otherwise I couldn't build.

Small precision, I deactivated all the roes and the r0 occurs when I pass level 74 -> level 75

same problem as  #2436 #2437 i think but i don't use gm command

In the log i have : Syntax error : Bad fd number 
--- gdb backtrace ---

**Comment by Chronos77** [comment]
Another test: i can lvl up 75 in a cap zone but when i leave zone cap => R0

**Comment by Chronos77** [comment]
Fix
