### ISSUE TITLE
Changejob 'new' bug (yet again)

### ISSUE THREAD

**Issue by Gradius2** [topaz-next/topaz#2436]
Due to the changes of job (for adopting GEO probably) now a simple !changejob war 99 (GM cmd) crashes the server.

My main (on char) is war level 1.

Yes, I'm on the last version (as now), last client, etc.

**Comment by Gradius2** [comment]
Just checked, !changejob war 75 also crashes the server.

However, lower lvl not (checking if <75 works).

Edit: confirmed, < 75 works.  Anything else crashes.

Regardless the use of subjob or not, it crashes the same way.

**Comment by Gradius2** [comment]
If I edit the DB manually to 99 (for example), everytime when I try to login, it crashes (interesting) after confirming which char I want to play (already inside on client).

**Comment by Gradius2** [comment]
Reverting the code back as pointed in:
https://github.com/topaz-next/topaz/pull/2423

File: src/map/merit.cpp

Didn't fixed the issue.  Something else has changed.

**Comment by TeoTwawki** [comment]
*picks up template*

Hi, looks like you dropped this:

> 
> **_I have:_**
>
> - [] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
> - [] checked the commit log to see if the issue has been resolved since my server was last updated
>
> **_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Anyway, this is likely related to recent _essential_ refactoring. I presume you are on the release branch?

**Comment by Gradius2** [comment]
"> _picks up template_"

No I didn't.  I just prefered omitted as I said "Yes, I'm on the last version (as now), last client, etc.".
 
I'm on official release:
https://github.com/topaz-next/topaz/archive/release.zip

**Comment by TeoTwawki** [comment]
that was humor, but no, don't omit that in the future. its pre-loaded for a reason. just tick the boxes and move on.

**Comment by Gradius2** [comment]
Humor?  Where?  Down vote for real?   Hmm, I can now see why fewer and fewer are leaving.  No incentive at all.

**Comment by TeoTwawki** [comment]
> 
> 
> Just checked, !changejob war 75 also crashes the server.
> 
> However, lower lvl not (checking if <75 works).
> 
> Edit: confirmed, < 75 works. Anything else crashes.
> 
> Regardless the use of subjob or not, it crashes the same way.

really strange that the level being 75 or greater is required to trip the bug.

**Comment by TeoTwawki** [comment]
> 
> 
> Humor? Where? Down vote for real? Hmm, I can now see why fewer and fewer are leaving. No incentive at all.

grow up. fewer and fewer have been in the pool of devs to join because of people starting off hostile and ignoring instruction exactly like you did here. I'm not a dev anymore and have no desire to ever be again, exactly because of crap I took from people daily. Everyone here is a volunteer, nobody gets paid for this. cram it where the sun doesn't shine.

p.s. downvoting isn't a thing. this isn't facebook reddit or highschool, its an thumbs down emote. disapproval. See? I can thumbs down my post too, doesn't mean squat.

**Comment by Gradius2** [comment]
@TeoTwawki no dude.  YOU should grow up.  I'm also a volunteer here, been looking for hours on boat/airship bug, and you are fire up over a simple template when I answered to that on a much simpler manner.  Anyway, I wouldn't waste more time on this.

**Comment by TeoTwawki** [comment]
no I'm "fire up" over you being a [censored], you threw a fit over being told to use it in the future and had a negative tone from the beginning. Ever seen someone accidental leave the "Arm" off their emoji and a reply going "hey is this your arm? I think you dropped this arm, here: `/` " ?

I was humorously noting you left off the template till you had your little tantrum over it, but its 2 clicks to check 2 boxes after saving your message. Don't waste anyone else's time and don't @ me

**Comment by zach2good** [comment]
For the two of you, and anyone passing by in the future:

The templates are there for a reason; please use them. It's less important for issues than for pull requests, but I had hoped the presence of a pre-filled template would encourage people to use them. I'll now add this to the rules so there is no more confusion.

Both of you please refresh yourselves on our Code of Conduct: <https://github.com/topaz-next/topaz/blob/release/CODE_OF_CONDUCT.md>

```
Our Standards
Examples of behavior that contributes to a positive environment for our community include:

Demonstrating empathy and kindness toward other people
Being respectful of differing opinions, viewpoints, and experiences
Giving and gracefully accepting constructive feedback
Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience
Focusing on what is best not just for us as individuals, but for the overall community
Examples of unacceptable behavior include:

The use of sexualized language or imagery, and sexual attention or advances of any kind
Trolling, insulting or derogatory comments, and personal or political attacks
Public or private harassment
Publishing others' private information, such as a physical or email address, without their explicit permission
Other conduct which could reasonably be considered inappropriate in a professional setting
```

I'm not going to start the [enforcement process](https://github.com/topaz-next/topaz/blob/release/CODE_OF_CONDUCT.md#enforcement-guidelines) with anyone just yet, this is a "friendly reminder" that this sort of behaviour won't be tolerated.

Feel free to message me on Discord if you're unhappy with how someone is behaving, or drop an email to topaz.next.project@gmail.com (full disclosure, this just forwards to me for now). 

Locking thread.
