### ISSUE TITLE
merit category bugs (see #2436)

### ISSUE THREAD

**Issue by TeoTwawki** [topaz-next/topaz#2437]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Tests by Claywar (thank you Claywar) indicate its dying out in CheckAbilityAddType() when it hits merit checks on warrior, reproducible by being on a different job and switching to warrior via `!changejob war <lv>` at a level where war would gain merits for tomahawk and warriors charge. Changing to warrior before using the command appears to allow it to work, as does setting a level below 75 (because no merit JAs).

**Comment by ghost** [comment]
This should be fixed by #2502 but needs confirmation.

**Comment by ghost** [comment]
Closing this issue from previous fix.  New defects to be tracked separately.
