### ISSUE TITLE
[sol_refactor] Range attack crash server

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2474]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Have Ranger 
Make a range attack

On the log i have see that : 
![image](https://user-images.githubusercontent.com/1618002/105169632-171e3680-5b1c-11eb-8220-a86422f574c7.png)

and when crash server:
[20/Jan] [11:28:58] [Fatal Error]  --- gdb backtrace ---

https://user-images.githubusercontent.com/1618002/105180967-80597600-5b2b-11eb-8353-bdd838bd4b9c.mp4

**Comment by zach2good** [comment]
Fixed: https://github.com/topaz-next/topaz/pull/2288/commits/1afea24b5bd861cb53d58879e0e09db8250b5c0e
