### ISSUE TITLE
[sol_refactor] Error on mobfight Eald'narche (ZM 16)

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2478]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] This issue occurs on `sol_refactor` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Start bcnm ZM16

![image](https://user-images.githubusercontent.com/1618002/105347107-b4de3800-5be6-11eb-9ffb-112ebfa4a781.png)

**Comment by zach2good** [comment]
Good find 👍 Thanks for doing all of this testing for this branch :)

**Comment by Chronos77** [comment]
It's a pleasure to test FFXI lol :D

**Comment by zach2good** [comment]
Should be fixed with: https://github.com/topaz-next/topaz/pull/2288/commits/0aeb5c2e50d9c9ef1f37dc7751b4de3032bcf17f
