### ISSUE TITLE
Testing: sol_refactor in canary

### ISSUE THREAD

**Issue by zach2good** [topaz-next/topaz#2483]
Since discussions aren't as supported as issues (yet!) , I'm making and pinning this issue so we can sanity check all the things that are wrong or broken in `canary` now that it's host to `sol_refactor`. This is also a really good opportunity to take stock of what works in general.

We've done pretty broad testing across the board as we've worked, but a focused effort would help stability a lot! This is not a carbon-copy of the "What Works" list, this is based on features that expose different areas of the codebase that have been modified. Packet handling, database interaction etc. haven't been touched, so don't need to be tested.

If you have edit power, please edit as you go :) If not, feel free to comment or ask someone else to fill in the list.

**This is not an audit/balance/implementation pass! This is just to confirm things are "as working" as they were before the refactor. If there are any quick wins along the way, great, but that isn't the main goal**

## Base Features
| Feature | Status |
|---|---|
| Melee Combat | ✅ |
| Melee Weapon skills | ✅ (H2H OK)  |
| Skillchains | ✅ |
| Self-Skillchains | ✅ |
| Ranged Combat | ✅ |
| Basic Spellcasting | ✅ |
| Zoning | ✅ |
| Homepoints| ✅ |
| Mounts | ✅ |
| NPC Interaction | ✅ |
| NPC Trading | ✅ |
| Basic Cutscenes | ✅ |
| Complex Cutscenes | |
| Bastok Elevators | ✅ |
| Mhuara/Selbina/AhtUrghan Boats | ✅ |
| Airships | ✅ |
| Items + Food | ✅ |
| Food Effects | ✅ |
| AdditionalEffects + En-Spells | ✅ |
| Scrolls | ✅ |
| Furniture | ✅ |
| Sky Gods |✅ |
| HELM | ✅ |
| Chocobo Digging | |
| Weather | ✅ |

## Complex Features
| Feature | Status |
|---|---|
| Conqust + OnGameHour Time Systems | ✅ |
| BCNM System | ✅ |
| Rank 2 Fight Fight | ✅ |
| Shadow Lord Fight | ✅ (A little janky, but fine) |
| Dawn Fight | ✅ (Prishe complains a lot, but fine) |
| Instance System | ✅ |
| TOAU44 (Nashmeira's Plea) Fight | ✅ |
| Bastok Missions | ✅ |
| Sandy Missions | |
| Windurst Missions | |
| Zilart Missions | ✅ |
| COP Missions | ✅ |
| TOAU Missions | |
| Dynamis | |
| Augments | |
| Crafting | |
| Mob mixins | ✅ |
| Zone mixins | ✅ |

## Jobs
| Feature | Status |
|---|---|
| WAR Abilities | |
| MNK Abilities | ✅ (All fine except Perfect Counter and Impetus: wrong messages and do nothing) |
| WHM Abilities + Spells | |
| BLM Abilities + Spells | |
| RDM Abilities + Spells | |
| THF Abilities | |
| PLD Abilities + Spells | |
| DRK Abilities + Spells | |
| BST Abilities + Pets| |
| BRD Abilities + Spells | |
| RNG Abilities | (These were in a bad way beforehand, cleanup would be great!) |
| SAM Abilities | |
| NIN Abilities + Spells | |
| DRG Abilities + Pets | |
| SMN Abilities + Pets | |
| BLU Abilities + Spells | |
| COR Abilities | |
| PUP Abilities + Pets | |
| DNC Abilities | |
| SCH Abilities + Spells | |
| GEO Abilities + Spells | exempt |
| RUN Abilities + Spells | exempt |

## Recent Content
| Feature | Status |
|---|---|
| ROE | ✅ |
| Magian Trials | ✅ |
| Hunts | |
| Trusts | ✅ |
| Full Speed Ahead | ✅ |

## Misc
| Feature | Status |
|---|---|
| GM Commands | ✅ |

**Comment by ghost** [comment]
@zach2good Can you provide an example of a good "complex" cutscene to test?  Long ones I think are covered (Dawn), and for events with updates, perhaps some sort of vendor?

**Comment by zach2good** [comment]
I pulled these categories off the top of my head, we've already covered some pretty complex CS scenarios so I think we're OK 👍

**Comment by Chronos77** [comment]
Magian trials are ok i have made Annihilator 95 :D.
I reported an error on the slip storages that worked before but not now.
CoP missions are ok after merge #2565 
ZM missions are ok.
Bastok Missions are ok.

**Comment by TeoTwawki** [comment]
@zach2good @claywar 

RE: complex cut scenes
 - Atma Infusionist
 - Synergy Furnace

Both of those are heavily `onEventUpdate` / `updateEvent` driven, I would call their cs events complex as F.

**Comment by TheWhaler** [comment]
Corsair Rolls seems to not function 100% correct.

- The roll on our server startup seems to always apply Avenger's roll regardless of what roll is used. Until you go directly to that script and edit it and save. It seems then the server recaches the ability and works
- Double-Up seems to always apply 0 to the current roll.

**Comment by ghost** [comment]
@TheWhaler RC'd the issues with corsair rolls.  Refactoring that code a bit, and should have a fix up soon.

**Comment by Chronos77** [comment]
I cannot complete the TOAU missions because I have a problem with the mission 15 The Black Coffin. I am well teleported to the intance however once the fight is over I am not teleported out and I stay on a black screen. Moreover, when I look at my position I find myself in the water (! Pos 0 0 0 60). Then some csid are not good.

however, I don't know if we have the same problem on the release branch.

**Comment by TheWhaler** [comment]
Puppetmaster attachments dont seem to be functioning. (Autorepair kit doesnt give regen to automaton)

**Comment by ghost** [comment]
Think I found the issue with PUP attachments (onUpdate was moved to the attachment_object table, but being called as local/global).  Going to see if I can clean up some of this to make life easier.

**Comment by zach2good** [comment]
We're probably OK to close this and address new issues as they're found :)
