### ISSUE TITLE
Chigoes cannot be targetable [Canary commit 908442d]

### ISSUE THREAD

**Issue by kaincenteno** [topaz-next/topaz#2487]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Fought elephant in wajaom woodland, then chigoe popped from it, afterwards it was unable to being targetted.
I was able to target it before so unsure if something changed with trusts or this is related to the sol-refactor.

**Comment by Era-Lusiphur** [comment]
Communicated via DMs with @claywar  , but posting for history here. Antlion nameplates are visible prior to Ambush/aggro. Once aggrod, they were not visible or targetable and just attacked player.

He is investigating mixins.

**Comment by ghost** [comment]
Bumping this off.  In a Phuabo test, it was surfacing, but I can't confirm that is from animation change.  After looking at the mixins items, I'm still trying to wrap my head around its intent after the update.

**Comment by zach2good** [comment]
Whoops! Wasn't applying mixins, fixed with: https://github.com/topaz-next/topaz/commit/74d17c81b687cbb6069f2e562716e5233cdfe0cd

Tested mixins with Aern's re-raising logic, so that works. Therefore, Chigoes should work as expected again:
```lua
g_mixins.families.chigoe = function(mob)
    mob:addListener("SPAWN", "CHIGOE_SPAWN", function(mob)
        mob:hideName(true)
        mob:untargetable(true)
    end)
    mob:addListener("ENGAGE", "CHIGOE_ENGAGE", function(mob, target)
        mob:hideName(false)
        mob:untargetable(false)
    end)
    mob:addListener("DISENGAGE", "CHIGOE_DISENGAGE", function(mob, target)
        mob:hideName(true)
        mob:untargetable(true)
    end)
end
```

Also, I think I previously saw Phuabo animations acting strangely, but now they were working OK when I was bashing Aerns 👍
