### ISSUE TITLE
InvalidGitRepositoryError(epath)

### ISSUE THREAD

**Issue by Gradius2** [topaz-next/topaz#2489]
- [X] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [X] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I'm trying a simple update... backup fail already:

C:\FFXI\tools>dbtool.py backup
Traceback (most recent call last):
  File "C:\FFXI\tools\dbtool.py", line 81, in <module>
    repo = Repo('../')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\git\repo\base.py", line 181, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: C:\FFXI

**Comment by kaincenteno** [comment]
did you install whats needed inside the requirements file? I think the wiki might need some explanation about how to do that as it doesnt mention installing pip

**Comment by Gradius2** [comment]
Yes, all requirements are installed (of course).

**Comment by Gradius2** [comment]
c:\FFXI\tools>pip install -r requirements.txt
Requirement already satisfied: mysql-connector-python in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 1)) (8.0.23)
Requirement already satisfied: gitpython in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 2)) (3.1.12)
Requirement already satisfied: pyyaml in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 3)) (5.4.1)
Requirement already satisfied: colorama in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 4)) (0.4.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from gitpython->-r requirements.txt (line 2)) (4.0.5)
Requirement already satisfied: smmap<4,>=3.0.1 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from gitdb<5,>=4.0.1->gitpython->-r requirements.txt (line 2)) (3.0.5)
Requirement already satisfied: protobuf>=3.0.0 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from mysql-connector-python->-r requirements.txt (line 1)) (3.14.0)
Requirement already satisfied: six>=1.9 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from protobuf>=3.0.0->mysql-connector-python->-r requirements.txt (line 1)) (1.15.0)

see?

**Comment by cocosolos** [comment]
[Did you clone the project using git?](https://github.com/topaz-next/topaz/wiki/Server-setup-and-maintenance-%5BWindows-10%5D#2-download-the-source-code) Downloading the zip file of the project is an unsupported installation and doesn't work properly.

**Comment by kaincenteno** [comment]
yeah i was gonna say that xD

**Comment by Gradius2** [comment]
The 1st install was made all manually.  The error is bc of that?

**Comment by kaincenteno** [comment]
yes because it's part of the script. just download it using git and should be resolved =)

**Comment by Gradius2** [comment]
I see.  Well, gotta use that from now on.

Thx
