### ISSUE TITLE
!pos y and z and swapped

### ISSUE THREAD

**Issue by Gradius2** [topaz-next/topaz#2490]
- [X] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [X] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Since this bug is still present, I'll mention again.

!pos Y and Z are still swapped.  Has no one noticed ?

**Comment by Gradius2** [comment]
Proof.
![img_20210124_223517](https://user-images.githubusercontent.com/11011463/105651069-8a190b80-5e94-11eb-9fdc-0832aa9ae332.jpg)

**Comment by Gradius2** [comment]
Proof...
![proff](https://user-images.githubusercontent.com/11011463/105651388-7c17ba80-5e95-11eb-82d4-90e142527167.png)

**Comment by wrenffxi** [comment]
The coordinates output by !pos are internally consistent with coordinates used everywhere in the project.  The coordinates output by infobar are flipped. Look at coordinates of the two NPCs you're standing next to:

![image](https://user-images.githubusercontent.com/21246949/105651978-41f2ec80-5e86-11eb-926e-56097226ef78.png)

**Comment by Gradius2** [comment]
That's weird, as BOTH addon, and plugin, shows Y & Z swapped, on windower, and I'm using the last version, fully updated.

**Comment by wrenffxi** [comment]
Both rely on windower field definitions, which always orders fields as X, Z, Y instead of X, Y, Z.
https://github.com/Windower/Lua/blob/63c294d17fe45bfaf2adcb48647804f686bdf916/addons/libs/packets/fields.lua#L1354-L1356

**Comment by Gradius2** [comment]
Yeah, I went on windower discord.  I can change on addon, but not on plugin as is just a .dll.

Its a shame, as the plugin shows the information much better than the addon.

**Comment by Gradius2** [comment]
Fixed by editing:
C:\windower\addons\InfoBar\data

File: settings.xml

`        <NoTarget>${name} (${main_job}${main_job_level}/${sub_job}${sub_job_level}) (${x},${z},${y})</NoTarget>`
