### ISSUE TITLE
Treasure Caskets not popping [Canary commit 908442d]

### ISSUE THREAD

**Issue by kaincenteno** [topaz-next/topaz#2492]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
After killing mobs, treasure casket blue or brown won't pop.
No settings were changed from the default.

**Comment by zach2good** [comment]
Fixed with: https://github.com/topaz-next/topaz/commit/a29085faddbc27ac57fa73fa1fbbded989a33a01

![image](https://user-images.githubusercontent.com/1389729/105670311-7fd52c80-5ee9-11eb-92ce-85ec11724074.png)
