### ISSUE TITLE
[canary] Crash server when log an existing character but create new character is ok

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2498]
- [ x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [ x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ x]  This issue occurs on `canary` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
![image](https://user-images.githubusercontent.com/1618002/105879044-02e9a600-6002-11eb-9723-742f3eab5698.png)

**Comment by Gradius2** [comment]
It can crash if that char was in a alpha state area for example.  It happend for me couple of times, in older release (darkstar one).

I had to enter on SQL and edit manually to a safe area (Jeuno for example), then I was able to log in (no crashes).

See if its the case.

**Comment by kaincenteno** [comment]
I havent been able to reproduce on Canaria (we are current with Canary commit 960bb5e).

We had two instances were server dropped everyone from server but it didn't crash. Currently running it on debug mode to try and get more info but nobody has reported issues on crashing server at log in. Will keep this in mind

**Comment by Chronos77** [comment]
Hi, 
I just found, it's a database export problem that I re-imported. however I did not use the dbtool (very bad idea lol). Sorry for this that. i will close that
