### ISSUE TITLE
Define a function inside the define?

### ISSUE THREAD

**Issue by Gradius2** [topaz-next/topaz#2499]
- [X] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [X] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Not a real issue... but is confusing.

Is this define a function inside the define ?

File: ..\src\map\lua\luautils.h

Lines: 41~43:
```
#define SOL_START(BaseTypeName, BindingTypeName) luautils::lua.new_usertype<BindingTypeName>(#BaseTypeName
#define SOL_REGISTER(Func) , #Func, &Func
#define SOL_END() );
```

**Comment by Gradius2** [comment]
Stetical / Cosmetical changes:
![space](https://user-images.githubusercontent.com/11011463/105916569-dfc5f300-600f-11eb-8980-619ecaeefc1b.jpg)

Hmm... is fully of it on scripts files, 74 files, 89 hits.

**Comment by zach2good** [comment]
If you have questions about the codebase, please ask them in Discord instead of reporting false issues.
