### ISSUE TITLE
Cannot Join BCNM as a guest to assist [Canary 960bb5e]

### ISSUE THREAD

**Issue by kaincenteno** [topaz-next/topaz#2515]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
* Have a character that already have defeated shadow lord.
* Have a friend that needs help with defeating shadow lord.
* Make a party
* Friend goes inside fight
- Expected behaviour: at the moment he/she/they go into fight, all party members should receive bcnm yellow icon. In this case only the person that started the BCNM does but not other party member.
* Touch door, nothing happens, no error in server log.
- Expected behaviour: touching door should allow you to join friend on fight,

**Comment by ghost** [comment]
This is most likely the same as #2395

**Comment by kaincenteno** [comment]
Ah darn i was looking for canary bugs sorry for creating duplicate >.< closing this one
