### ISSUE TITLE
Doing CoP mission for fun... until...

### ISSUE THREAD

**Issue by Gradius2** [topaz-next/topaz#2516]
- [X] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [X] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Well, now I was doing CoP mission for fun, everything was w/o any problem, until I "The Road Forks".

On Exit Stage Left (3-3B3) stage:

I forgot to talk to Tosuka-Porika.  I went for Yoran-Oran then Cid, after zoning Lower Jeuno I see "Tending Aged Wounds", wasn't flagged, so I tried to do it manually anyway, I did !addmission 6 31 Gradius.

Seeing the server, got error another mission was flagged already, so I decided to delete the entire CoP by using !delmission 6 from 0 to 31.  Then I did  !addmission 6 31 Gradius.  My Mission tab on client has nothing flagged for Promathia, even restarting the server and trying !addmission 6 31 again.

It should at least flag the TENDING_AGED_WOUNDS mission, if I'm forcing by command.  But nothing happens.

**Comment by Gradius2** [comment]
More findings...

If I go to Lower_Delkfutts_Tower I'm able to get the very first CS from CoP mission.

But then, if I do !addmission 6 31 Gradius (after CS), I get no mission at all on CoP again (missions > promathia).

**Comment by wrenffxi** [comment]
COP missions have [values between 101 and 850](https://github.com/topaz-next/topaz/blob/7b30255b9e805b82cfed878486b05ecf840191f3/scripts/globals/missions.lua#L189-L258).

You can also use text instead of numbers:
`!delmission COP TENDING_AGED_WOUNDS` 
`!addmission COP TENDING_AGED_WOUNDS`

**Comment by Gradius2** [comment]
I see.  The IDs changed a lot.  I was using the old wiki from D.S.

Thanks a lot, !addmission COP did the trick.
