### ISSUE TITLE
[canary] Issue on treasure chest

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2534]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] This issue occurs on `canary` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Resolve treasure chest after kill a mob
![image](https://user-images.githubusercontent.com/1618002/106352525-2ce1e780-62e4-11eb-9d4c-2bb09a7834eb.png)

**Comment by Xaver-DaRed** [comment]
In short, the issue is...
it told you the "first digit" when it should have been the "second digit"
OR
it showed a 0 when it should have been a 2 (First digit cannot be 0 ever)

First case could be caused by a textID missmatch.
Knowing wich zone you were in and if it happens in other zones and your client version might help.

**Comment by Chronos77** [comment]
Hi, i'm in kuftal tunnel, i will try in another zone .
![image](https://user-images.githubusercontent.com/1618002/106353136-a5e33e00-62e8-11eb-8784-594191f6948d.png)

**Comment by Chronos77** [comment]
Same in West Sarutabaruta 

![image](https://user-images.githubusercontent.com/1618002/106353223-3ae63700-62e9-11eb-811c-236c4b57c40f.png)

**Comment by Xaver-DaRed** [comment]
So in short, now we know that its returning a 0 instead of the actual number.
And it seems like it is the **correct** number that is being turned to a 0

**Comment by wrenffxi** [comment]
My guess is the problem is that splitNumbers[1] is string.  Probably needs change from

```
                        player:messageSpecial(baseMessage + casketInfo.messageOffset.FIRST_DIGIT_IS,
                            splitNumbers[1],
                            splitNumbers[1] +1,
                            splitNumbers[1] +2, 0)
```
 to

```
                        player:messageSpecial(baseMessage + casketInfo.messageOffset.FIRST_DIGIT_IS,
                            splitNumbers[1] +0,
                            splitNumbers[1] +1,
                            splitNumbers[1] +2, 0)
```
wherever it's being passed as argument into messageSpecial
will fix tomorrow if nobody beats me to it

**Comment by Chronos77** [comment]
It's works! 
![image](https://user-images.githubusercontent.com/1618002/106596841-daa7fd00-6555-11eb-9034-567ca5f842d0.png)
