### ISSUE TITLE
Food Effects are not working in Canary d0c8ef3

### ISSUE THREAD

**Issue by AuroraFlare** [topaz-next/topaz#2552]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] This issue occurs on `release` branch (if other branch, please specify) - Canary branch

When using food we get the effect icon but no stats seem to be working.
I'm using Canary d0c8ef3

**Comment by zach2good** [comment]
Nice find 👍 

Now fixed in `canary`: https://github.com/topaz-next/topaz/commit/fcae69738d2b45bcb070ef50f10bd30bb39016d8
