### ISSUE TITLE
[canary] crash serveur when  Pinging server to keep connection alive

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2608]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

```
[10/Feb] [19:02:49] [Info]  parse: 03A | C491 C44D 04 from user: Cristena
[10/Feb] [19:03:20] [Info]  parse: 0B5 | 05F2 05EE 12 from user: Fleme
[10/Feb] [19:03:21] [Info]  parse: 03A | C4D9 C495 04 from user: Cristena
[10/Feb] [19:07:19] [Info]  Pinging SQL server to keep connection alive...
[10/Feb] [19:07:19] [Fatal Error]  --- gdb backtrace ---
```

**Comment by ghost** [comment]
@Chronos77 Would it be possible to get the trace info from the dump?  Without that, it'll be fairly difficult to RC.

**Comment by Chronos77** [comment]
Where can I find this dump please?

**Comment by Chronos77** [comment]
I will close this ticket because I cannot reproduce it, moreover I think it came from the infrastructure of my server. 
My mysql was accessible from the outside, I saw in the logs that I had a lot of connection attempts so I made it inaccessible from the outside and I could not this problem.
