### ISSUE TITLE
Error on compiling game server

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2637]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

PS: I wasn't sure if I should make an issue or posted this in the discord. After if other people find themselves in the same case as me and there is a solution at least it will be shared :)

Hello, wanting to try to debug the game_server, I launched the project with visual studio 2019

![image](https://user-images.githubusercontent.com/1618002/107891494-465b7400-6f1f-11eb-83a2-8dd8222b6053.png)

and when i try to compile the game_server i have theses error (sorry it's in french lol)

![image](https://user-images.githubusercontent.com/1618002/107891687-866f2680-6f20-11eb-8a6d-fa4e0bf5311d.png)

I did a lot of research however nothing conclusive, have you ever had this problem? I may have forgotten to install something or a configuration problem on Visual studio 2019.

PS2: this is the first time i try to compile the server from my pc, otherwise I have a windows 10 pro (64 bits)

thank you in advance for your help

**Comment by kaincenteno** [comment]
Did you follow the new CMake build guide?

https://github.com/topaz-next/topaz/wiki/CMake-Build-Guide

**Comment by Chronos77** [comment]
yes i have try with this build guide.

i try  with cmake ..  and cmake .. -A Win32

this is the log for win32

```$ cmake .. -A Win32
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
-- The CXX compiler identification is MSVC 19.20.27508.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x86/cl.exe -- works        
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_SOURCE_DIR: D:/projects/topaz-1
-- CMAKE_SIZEOF_VOID_P == 4: 32-bit build
-- CLANG_FORMAT_BIN: CLANG_FORMAT_BIN-NOTFOUND
-- TRACY_ENABLE: OFF
-- CMAKE_VERSION: 3.14.3
-- CMAKE_BUILD_TYPE:
-- CMAKE_C_COMPILER:
-- CMAKE_CXX_COMPILER: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x86/cl.exe
-- CMAKE_CXX_COMPILER_ID: MSVC
-- CMAKE_CXX_COMPILER_VERSION: 19.20.27508.1
-- CMAKE_CXX_FLAGS: /DWIN32 /D_WINDOWS /GR /EHsc -D_CONSOLE -D_MBCS -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE /Oy- /MP /Oi /GL /Gy /TP
-- CMAKE_GENERATOR: Visual Studio 16 2019
-- CMAKE_GENERATOR_PLATFORM: Win32
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
-- Found Threads: TRUE  
-- Found MySQL: C:/Program Files/MariaDB/MariaDB Connector C 64-bit/lib/libmariadb.lib  
-- MYSQL_FOUND: TRUE
-- MYSQL_LIBRARY: C:/Program Files/MariaDB/MariaDB Connector C 64-bit/lib/libmariadb.lib
-- MYSQL_INCLUDE_DIR: D:/projects/topaz-1/ext/mysql/include/mysql
-- Found ZeroMQ: D:/projects/topaz-1/ext/zmq/lib/libzmq.lib  
-- ZeroMQ_FOUND: TRUE
-- ZeroMQ_LIBRARY: D:/projects/topaz-1/ext/zmq/lib/libzmq.lib 
-- ZeroMQ_INCLUDE_DIR: D:/projects/topaz-1/ext/zmq/include/zmq
-- Found LuaJIT: D:/projects/topaz-1/ext/lua/lib/libluajit.lib  
-- LuaJIT_FOUND: TRUE
-- LuaJIT_LIBRARY: D:/projects/topaz-1/ext/lua/lib/libluajit.lib
-- LuaJIT_INCLUDE_DIR: D:/projects/topaz-1/ext/lua/include      
-- ENABLE_CLANG_TIDY: OFF
-- ENABLE_CLANG_TIDY_AUTO_FIX: OFF
-- Setting output directory for topaz_connect to D:/projects/topaz-1
-- Setting output directory for topaz_game to D:/projects/topaz-1
-- Setting output directory for topaz_search to D:/projects/topaz-1
-- Configuring done
-- Generating done
-- Build files have been written to: D:/projects/topaz-1/build```

my compiler may be?

**Comment by Chronos77** [comment]
Okay, I found, I had two versions installed the 2017 and 2019, I uninstall the two and reinstall the 2019 with the tools for C ++ and it's works! let's go debugging! thanks all :)
