### ISSUE TITLE
NPC Pathing more broken than before [Canary a7a0283]

### ISSUE THREAD

**Issue by kaincenteno** [topaz-next/topaz#2641]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

It was brought to me that Raminel for GENKAI4 couldnt be found anywhere. I did !gotoid and found him floating in the air. To confirm if this happened to another pathing npc, I went to pay a visit to Red Ghost that can also be found floating in the air.

Before Pathing NPC wouldnt continue patroling and once they reached their last co-ordinate they will just stay permanent in that place. 

![raminel](https://user-images.githubusercontent.com/26943220/108092907-05a04f80-7032-11eb-9343-dfda2d56e7ee.png)

![red_ghost](https://user-images.githubusercontent.com/26943220/108092945-0d5ff400-7032-11eb-8b10-359ddab41e15.png)

**Comment by TeoTwawki** [comment]
Raminel you get back down here this instant! You'll give your poor mother a heart attack!

Red Ghost what kind of example are you setting for the children? knock that off!

**Comment by kaincenteno** [comment]
Cadwyn in Canaria reported that this also happens to Novalmauge in Bostaunieux Oubliette
We just updated to Canary 385ac9a

**Comment by ghost** [comment]
I wonder, are we mucking up axes now after the refactor?

**Comment by RAIST5150** [comment]
It appears enemies that teleport during fight may fall through the floor now as well... may be limited to enemies that hover?  Experienced it with both Ark Angel Taru Taru and Apocalypse Nigh's Eald'narche.

Could still target and cast on AATT if you stood over her, and she would eventually port back to you with this tactic.

But the little brother was nowhere to be found--guessing he fell down to Qufim.  Wound up having to use a stun lock tactic from outside aggro range at start of fight to keep him in place while finishing him off.

**Comment by kaincenteno** [comment]
@claywar + @zach2good  is it okay if I open a PR commenting out their patrol/pathing behavior and placing a link to this issue for all those NPCs that are affected? I ask as this is a known issue for a couple years that I dont think is in the TODO list.

**Comment by ghost** [comment]
I would prefer we fix the issue.  Raminel was working during initial sol tests, so I don't think this is something very old.

**Comment by SirGouki** [comment]
this is likely the cause of #2603
