### ISSUE TITLE
lua FileWatcher is only enabled on x86 debug builds, not all debug builds

### ISSUE THREAD

**Issue by SirGouki** [topaz-next/topaz#2645]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
When compiling the map server, the file watcher by default is only enabled if the target is x86 debug.  It will not enable the file watcher if the target is x64 debug.

Workaround:
remove/comment out the preprocessor code
`#ifdef DEBUG`
and
`#endif`
that are around `luautils::EnableFileWatcher()`, but this will make it active on all builds.  I don't know the proper flag for Windows' 64 debug build.

**Comment by ghost** [comment]
Definitely enabled on my end with an x64 debug build using VS2019.  What build flags are you using?

**Comment by SirGouki** [comment]
Whatever the default were, I used the cmake to import it into VS2019 community, and just changed it to x64 Debug.
I have not changed the default stuff VS adds as far as build flags are concerned.

**Comment by zach2good** [comment]
I thought hiding the filewatcher stuff inside debug builds was snazzy, but in the end its even annoying me as I try to build/rebuild etc. I'll enable it everywhere soon 👍 

As for flags, 32/64 shouldn't change anything, but I _THINK_ the debug flag is officially: `_DEBUG`, but I don't remember

Won't matter soon anyway

**Comment by zach2good** [comment]
Fixed with: https://github.com/topaz-next/topaz/commit/e27b448239e33cc707ca5680947aa0161098d6c4
