### ISSUE TITLE
Trust quests crashing client

### ISSUE THREAD

**Issue by shawnsoup** [topaz-next/topaz#2656]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] This issue occurs on `release` branch (if other branch, please specify)

Doing trust quest is crashing my client. I've tried on multiple characters, and all three zones. Sandy seems to be the most stable, but at some point after starting the trust quest my client will crash. When attempting to or within 1 minute after talking to the first NPC (Naji, Kupi, Excen).

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
I completely rebuilt the server. Loaded backup lite database. I created a new character got it to level 5 and started the trust quest, as soon as I click Kupipi in Heaven's tower my client crashes.  Inserted photo of game server during the crash. 
![hmm](https://user-images.githubusercontent.com/78249521/108906134-8c36cd00-75ee-11eb-8496-17655c4b1c54.PNG)

**Comment by kaincenteno** [comment]
If you are running your server on linux and install `gdb` then run it with `gdm topaz_game` (i dunno how to run it with debug on windows =( )

**Comment by TeoTwawki** [comment]
For windows folks its just open visual studio and attach to debugger then try to crash on purpose -or- if proper configured crash happens and vs auto pops(or auto saves dump) and shows you debug info

**Comment by kaincenteno** [comment]
@TeoTwawki  is there a guide on how to attach the debugger/configure crash so @shawnsoup  can get that info? :smile_cat:

**Comment by ghost** [comment]
Hello,

here: https://github.com/topaz-next/topaz/wiki/Debugging#how-to-make-a-dump-file-with-visual-studio-2019.

**Comment by kaincenteno** [comment]
Thank you ❤️😊

**Comment by shawnsoup** [comment]
Not sure if I did this correctly, but this is what the dump says

![8gf](https://user-images.githubusercontent.com/78249521/108921186-fad25580-7603-11eb-81bf-f15dc87d008f.PNG)

**Comment by TeoTwawki** [comment]
> 
> Not sure if I did this correctly, but this is what the dump says
> 

you'll need to link/attach the dmp, pdb, and exe files (I woudl 7zip the 3 together) to the post for someone to look at. The screenshot gives no useful info. Loading a dump into vs lets us look at the call stack and then we can more easily pinpoint what went kaboom. All 3 must match so if you rebuild causing vs to write new pdb and exe the dmp is no longer usable.

**Comment by ghost** [comment]
Note: This is a client crash, and not server (from the issue report).  If you're the only person on the server, can you try to provide specific steps for when this crash occurs (and perhaps actions leading up to it)?

**Comment by shawnsoup** [comment]
> Note: This is a client crash, and not server (from the issue report). If you're the only person on the server, can you try to provide specific steps for when this crash occurs (and perhaps actions leading up to it)?

Yeah it's a client crash. It's only me on the server, but I do multibox on it, and when the crash happens all the other clients are fine. So I go to any of the trust starter quest, get the permit, and after talking to the first trust (Kupipi, Naji, Excen), I go out to X starter area, cast the trust, then I go back and talk to them, after I get the trust server crashes. Sometimes the crash is immediate, sometimes it takes as much as 5 seconds or so. But it crashes every time. After that it happens any time I try to unlock a trust, I get the trust, it just crashes after. I've tried it while not multiboxing thinking it was a conflict with the clients, but it also crashes while I only have one client up. It's not a huge deal, like I said I play alone, the first two characters I did trust quests worked perfectly. Didn't touch anything updates wise and the last few have had this issue.

**Comment by TeoTwawki** [comment]
> Note: This is a client crash, and not server **(from the issue report).**

Oopsie, didn't catch it >.> usually crash reports here are server side since that's the part we code here.

Can't dump client side crashes (unless someone in this thread secretly works at SE) so these are a lot harder to pinpoint and often aren't fixable at our end - so many things can cause them, and 90% of them aren't from anything we did/do in the server side (most often damaged client or an addon/plugin). The remaining 10% that are the server's fault are usually very difficult to trace.

Is it just a sudden exit of the client or doe sit pop an error message in windows first?

**Comment by shawnsoup** [comment]
> Is it just a sudden exit of the client or doe sit pop an error message in windows first?

It's a sudden crash. But I'm going to do further testing when I get home now. I just thought it might have been server side since the quest was fine the first two characters I did it on and clients were fine. But Ill try opening my server to outside connections and do the quest from a fresh client install on another PC.

**Comment by shawnsoup** [comment]
Sorry for the inconveniences to anyone, but this issue has resolved itself on my end. Did a fresh install of everything (even though I had done this before) and quests seem to be working fine now, just tried on 4 different new characters. So closing now.
