### ISSUE TITLE
[release] Mob tp skills that cause sleep incorrectly cause sleep before damage instead of after

### ISSUE THREAD

**Issue by SirGouki** [topaz-next/topaz#2663]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Not sure how many of these are effected but I'm working on it.  To easily reproduce, fight a mob with one of these skills (like an ochu), after locking them into only being able to use that skill (ochu = Sweet Breath).  When the sleep finally sticks, the damage caused by the skill will immediately wake up the targets that were hit.  It's simply a problem of functions being called in the wrong order.  I opened this for tracking purposes.

**Comment by SirGouki** [comment]
Fixed Sweet Breath.  Working on looking through all the affected skills.

**Comment by ShiyoKozuki** [comment]
https://ffxiclopedia.fandom.com/wiki/Kartstrahl

**Comment by SirGouki** [comment]
Not sure what you're getting at with that link.

**Comment by SirGouki** [comment]
testing kartstrahl, pinecone bomb, and cyclone wing.

**Comment by ShiyoKozuki** [comment]
It's supposed to damage then sleep, it currently is bugged like sweet breath.
I'm sure pinebomb bomb and cyclone wing are the same.

**Comment by TeoTwawki** [comment]
#2664 

Note this won't work for older servers using the old core. Your only choice is to get updated. There **IS NO** script only fix for you if you are on the old core. Period.

**Comment by SirGouki** [comment]
All testing is done, all 4 mentioned mob abilities are now functioning the way they should be locally.  Teo submitted PR for this already, so we're just waiting on the merge.

**Comment by SirGouki** [comment]
PR #2664 solves this, I'm closing this issue.
