### ISSUE TITLE
Not enough gil for CSes

### ISSUE THREAD

**Issue by Gradius2** [topaz-next/topaz#2666]
- [X] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [X] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

This bug has been for a while now, and wasn't still fixed.

While I have max out the gil amount, I cannot watch any CS from Bards.

![img_20210228_014307](https://user-images.githubusercontent.com/11011463/109408283-b1b53500-7966-11eb-8da8-201218df8685.jpg)

**Comment by Gradius2** [comment]
Even if I set my gil to mere $1000, I get the same error.

**Comment by kaincenteno** [comment]
the issue is that they are not scripted =(

**Comment by Gradius2** [comment]
I see.
